/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsCheckoutRouteImport } from './routes/analytics.checkout'
import { Route as ApiPublicTrackCheckoutClickRouteImport } from './routes/api/public/track-checkout-click'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsCheckoutRoute = AnalyticsCheckoutRouteImport.update({
  id: '/analytics/checkout',
  path: '/analytics/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackCheckoutClickRoute =
  ApiPublicTrackCheckoutClickRouteImport.update({
    id: '/api/public/track-checkout-click',
    path: '/api/public/track-checkout-click',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics/checkout': typeof AnalyticsCheckoutRoute
  '/api/public/track-checkout-click': typeof ApiPublicTrackCheckoutClickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics/checkout': typeof AnalyticsCheckoutRoute
  '/api/public/track-checkout-click': typeof ApiPublicTrackCheckoutClickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics/checkout': typeof AnalyticsCheckoutRoute
  '/api/public/track-checkout-click': typeof ApiPublicTrackCheckoutClickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analytics/checkout' | '/api/public/track-checkout-click'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analytics/checkout' | '/api/public/track-checkout-click'
  id:
    | '__root__'
    | '/'
    | '/analytics/checkout'
    | '/api/public/track-checkout-click'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsCheckoutRoute: typeof AnalyticsCheckoutRoute
  ApiPublicTrackCheckoutClickRoute: typeof ApiPublicTrackCheckoutClickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/checkout': {
      id: '/analytics/checkout'
      path: '/analytics/checkout'
      fullPath: '/analytics/checkout'
      preLoaderRoute: typeof AnalyticsCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track-checkout-click': {
      id: '/api/public/track-checkout-click'
      path: '/api/public/track-checkout-click'
      fullPath: '/api/public/track-checkout-click'
      preLoaderRoute: typeof ApiPublicTrackCheckoutClickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsCheckoutRoute: AnalyticsCheckoutRoute,
  ApiPublicTrackCheckoutClickRoute: ApiPublicTrackCheckoutClickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
